apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice2
  template:
    metadata:
      labels:
        app: myservice2
    spec:
      containers:
        - name: myservice2
          image: theopruski/myservice2:1
          imagePullPolicy: Always
